# Generated by Django 2.1.15 on 2020-10-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('vel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
